[build]
  command = "npm run build"  # Run the Vite build to generate the dist folder
  publish = "dist"           # Set the publish directory to dist, where index.html is located

[[rewrites]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Keep your existing headers and other settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
